apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dummy-fim
spec:
  selector:
    matchLabels:
      app: dummy-fim
      pci-scope: out-of-scope
  template:
    metadata:
      labels:
        app: dummy-fim
        pci-scope: out-of-scope
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dummy-fim
        image: busybox
        args: [/bin/sh, -c, 'while true; do echo Placeholder FIM $(date); sleep 240; done']
        resources:
          limits:
            memory: "28Mi"
            cpu: "100m"
          requests:
            memory: "14Mi"
            cpu: "50m"
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: CriticalAddonsOnly
          effect: NoSchedule
          operator: Equal
          value: "true"
