  
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 3Gi
    requests.storage: "0"
    limits.cpu: "12"
    limits.memory: 10Gi
    count/persistentvolumeclaims: "0"
    count/services.loadbalancers: "0"
    count/services.nodeports: "0"
    count/deployments.apps: "0"
            
    # dummy-av, dummy-fim
    # kured
    count/daemonsets.apps: "3"
    count/services: "0"

    # dummy-av (1*[all nodes] = 7)
    # dummy-fim (1*[all nodes] = 7)
    # kured (1*[all nodes] = 7)
    # x~1.5 for scale out / rolling upgrades
    count/pods: "44"