apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: traffictargets.access.smi-spec.io
spec:
  group: access.smi-spec.io
  scope: Namespaced
  names:
    kind: TrafficTarget
    shortNames:
      - tt
    plural: traffictargets
    singular: traffictarget
  version: v1alpha3
  versions:
    - name: v1alpha3
      served: true
      storage: true
    - name: v1alpha2
      served: false
      storage: false
    - name: v1alpha1
      served: false
      storage: false
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - destination
            - rules
            - sources
          properties:
            destination:
              description: The destination of this traffic target.
              type: object
              required:
                - name
                - kind
              properties:
                kind:
                  description: Kind of the destination.
                  type: string
                name:
                  description: Name of the destination.
                  type: string
                namespace:
                  description: Namespace of the destination.
                  type: string
            rules:
              description: Specifications of this traffic target.
              type: array
              items:
                type: object
                required:
                  - name
                  - kind
                properties:
                  kind:
                    description: Kind of this spec.
                    type: string
                    enum:
                      - HTTPRouteGroup
                      - TCPRoute
                      - UDPRoute
                  name:
                    description: Name of this spec.
                    type: string
                  matches:
                    description: Match conditions of this spec.
                    type: array
                    items:
                      type: string
            sources:
              description: Sources of this traffic target.
              type: array
              items:
                type: object
                required:
                  - name
                  - kind
                properties:
                  kind:
                    description: Kind of this source.
                    type: string
                  name:
                    description: Name of this source.
                    type: string
                  namespace:
                    description: Namespace of this source.
                    type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: httproutegroups.specs.smi-spec.io
spec:
  group: specs.smi-spec.io
  scope: Namespaced
  names:
    kind: HTTPRouteGroup
    shortNames:
      - htr
    plural: httproutegroups
    singular: httproutegroup
  version: v1alpha4
  versions:
    - name: v1alpha4
      served: true
      storage: true
    - name: v1alpha3
      served: false
      storage: false
    - name: v1alpha2
      served: false
      storage: false
    - name: v1alpha1
      served: false
      storage: false
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - matches
          properties:
            matches:
              description: Match conditions of this route group.
              type: array
              items:
                type: object
                required:
                  - name
                properties:
                  name:
                    description: Name of the HTTP route.
                    type: string
                  pathRegex:
                    description: URI path regex of the HTTP route.
                    type: string
                  methods:
                    description: The HTTP methods of this HTTP route.
                    type: array
                    items:
                      type: string
                      description: The HTTP method of this HTTP route.
                      enum:
                        - '*'
                        - GET
                        - HEAD
                        - PUT
                        - POST
                        - DELETE
                        - CONNECT
                        - OPTIONS
                        - TRACE
                        - PATCH
                  headers:
                    description: Header match conditions of this route.
                    type: array
                    items:
                      description: Header match condition of this route.
                      type: object
                      additionalProperties:
                        type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tcproutes.specs.smi-spec.io
spec:
  group: specs.smi-spec.io
  scope: Namespaced
  names:
    kind: TCPRoute
    shortNames:
      - tr
    plural: tcproutes
    singular: tcproute
  version: v1alpha4
  versions:
    - name: v1alpha4
      served: true
      storage: true
    - name: v1alpha3
      served: false
      storage: false
    - name: v1alpha2
      served: false
      storage: false
    - name: v1alpha1
      served: false
      storage: false
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - matches
          properties:
            matches:
              description: Match conditions of this route.
              type: object
              required:
                - ports
              properties:
                ports:
                  description: Port numbers to match TCP traffic.
                  type: array
                  items:
                    type: integer
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: udproutes.specs.smi-spec.io
spec:
  group: specs.smi-spec.io
  scope: Namespaced
  names:
    kind: UDPRoute
    shortNames:
      - ur
    plural: udproutes
    singular: udproute
  version: v1alpha4
  versions:
    - name: v1alpha4
      served: true
      storage: true
    - name: v1alpha3
      served: false
      storage: false
    - name: v1alpha2
      served: false
      storage: false
    - name: v1alpha1
      served: false
      storage: false
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - matches
          properties:
            matches:
              description: Match conditions of this route.
              type: object
              required:
                - ports
              properties:
                ports:
                  description: Port numbers to match UDP traffic.
                  type: array
                  items:
                    type: integer
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: trafficsplits.split.smi-spec.io
spec:
  group: split.smi-spec.io
  version: v1alpha2
  scope: Namespaced
  names:
    kind: TrafficSplit
    listKind: TrafficSplitList
    shortNames:
    - ts
    plural: trafficsplits
    singular: trafficsplit
  versions:
  - name: v1alpha2
    served: true
    storage: true
  additionalPrinterColumns:
  - name: Service
    type: string
    description: The apex service of this split.
    JSONPath: .spec.service
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
            - service
            - backends
          properties:
            service:
              description: The apex service of this split.
              type: string
            backends:
              description: The backend services of this split.
              type: array
              items:
                type: object
                required: ['service', 'weight']
                properties:
                  service:
                    description: Name of the Kubernetes service.
                    type: string
                  weight:
                    description: Traffic weight value of this backend.
                    type: number
