  
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
spec:
  hard:
    requests.cpu: "0"
    requests.memory: 0Gi
    requests.storage: "0"
    limits.cpu: "0"
    limits.memory: 0Gi
    count/persistentvolumeclaims: "0"
    count/services.loadbalancers: "0"
    count/services.nodeports: "0"
    count/deployments.apps: "0"
    count/daemonset.apps: "0"
    count/services: "1"
    count/pods: "0"