apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
spec:
  hard:
    # 100m - microservice-a
    # 100m - microservice-b
    # 200m - Allow for x2 horizontal growth on above
    # 100m - Rolling updates
    requests.cpu: 500m

    # 200Mi - microservice-a
    # 200Mi - microservice-b
    # 400Mi - Allow for x2 horizontal growth on above
    # 200Mi - Rolling updates
    requests.memory: 1Gi
    requests.storage: "0"

    # 400m - microservice-a
    # 400m - microservice-b
    # 800m - Allow for x2 horizontal growth on above
    # 400m - Rolling updates
    limits.cpu: 2000m

    # 800Mi - microservice-a
    # 800Mi - microservice-b
    # 1600Mi - Allow for x2 horizontal growth on above
    # 800Mi - Rolling updates
    limits.memory: 4Gi
    count/persistentvolumeclaims: "0"
    count/services.loadbalancers: "0"
    count/services.nodeports: "0"

    # 1 - microservice-a
    # 1 - microservice-b
    count/deployments.apps: "2"
    count/daemonset.apps: "0"

    # 1 - microservice-a
    # 1 - microservice-b
    count/services: "2"

    # 2 - microservice-a
    # 2 - microservice-b
    # 4 - Allow for x2 horizontal growth on above
    # 2 - Rolling updates
    count/pods: "10"