apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-secrets-store-provider-azure
  labels:
    app.kubernetes.io/name: csi-secrets-store-provider-azure
    app.kubernetes.io/component: csi-provider
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: csi-secrets-store-provider-azure
    pci-scope: out-of-scope
  name: csi-secrets-store-provider-azure
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: csi-secrets-store-provider-azure
      pci-scope: out-of-scope
  template:
    metadata:
      labels:
        app: csi-secrets-store-provider-azure
        app.kubernetes.io/name: csi-secrets-store-provider-azure
        app.kubernetes.io/component: csi-provider
        pci-scope: out-of-scope
    spec:
      serviceAccountName: csi-secrets-store-provider-azure
      hostNetwork: true
      containers:
        - name: provider-azure-installer
          image: mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.12
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=unix:///provider/azure.sock
            - --construct-pem-chain=false  # Documentation: https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/feature-flags/#construct-pem-chain-feature-flag
          lifecycle:
            preStop:
              exec:
                command:
                  - "rm /provider/azure.sock"
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=unix:///provider/azure.sock"]
            initialDelaySeconds: 3
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=unix:///provider/azure.sock"]
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 150Mi
          volumeMounts:
            - mountPath: "/provider"
              name: providervol
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: HostToContainer
      volumes:
        - name: providervol
          hostPath:
            path: "/etc/kubernetes/secrets-store-csi-providers"
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
