---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: regulated
  url: https://github.com/REPLACE_ME_WITH_YOUR_GITHUBACCOUNTNAME/aks-secure-baseline
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster-manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
