apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falco-system
resources:
- namespace.yaml
- limit-range.yaml
- resource-quota.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- serviceaccount.yaml
- configmap.yaml
- daemonset.yaml
images:
- name: docker.io/falcosecurity/falco-no-driver
  newName: REPLACE_ME_WITH_YOUR_ACRNAME.azurecr.io/live/falcosecurity/falco-no-driver
- name: docker.io/falcosecurity/falco-driver-loader
  newName: REPLACE_ME_WITH_YOUR_ACRNAME.azurecr.io/live/falcosecurity/falco-driver-loader
