  
apiVersion: v1
kind: LimitRange
metadata:
  name: default
spec:
  limits:
  - max:
      cpu: 11500m
      memory: 1512Mi
    min:
      cpu: 0m
      memory: 0Mi
    default:
      cpu: 0m
      memory: 0Mi
    defaultRequest:
      cpu: 0m
      memory: 0Mi
    type: Container
  - max:
      storage: 0Mi
    min:
      storage: 0Mi
    type: PersistentVolumeClaim