kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha3
metadata:
  name: microservice-b
  labels:
    app.kubernetes.io/name: a0005
    app.kubernetes.io/component: microservice-b
    pci-scope: out-of-scope
spec:
  destination:
    kind: ServiceAccount
    name: microservice-b-sa
    namespace: a0005-o
  rules:
  - kind: HTTPRouteGroup
    name: microservice-b
    matches:
    - url-caller
  sources:
  - kind: ServiceAccount
    name: microservice-a-sa
    namespace: a0005-o
---
apiVersion: specs.smi-spec.io/v1alpha4
kind: HTTPRouteGroup
metadata:
  name: microservice-b
  labels:
    app.kubernetes.io/name: a0005
    app.kubernetes.io/component: microservice-b
    pci-scope: out-of-scope
spec:
  matches:
  - name: url-caller
    pathRegex: /URLCaller/depth/.+
    methods:
    - GET