apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: a0005-o
resources:
- networkpolicy.yaml
- allowed-traffic.yaml
- deployment.yaml
images:
- name: YOUR_ACR.azurecr.io/live/a0005/chain-api
  newName: REPLACE_ME_WITH_YOUR_ACRNAME.azurecr.io/live/a0005/chain-api