---
# Source: falco/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aks-falco
  labels:
    app: aks-falco
    chart: "falco-1.7.3"
    release: "aks"
    heritage: "Helm"
subjects:
  - kind: ServiceAccount
    name: aks-falco
    namespace: falco-system
roleRef:
  kind: ClusterRole
  name: aks-falco
  apiGroup: rbac.authorization.k8s.io
