---
# Source: falco/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aks-falco
  namespace: falco-system
  labels:
    app: aks-falco
    chart: "falco-1.6.0"
    release: "aks"
    heritage: "Helm"
