---
# Source: https://github.com/falcosecurity/deploy-kubernetes/blob/0faf1e702b4f4508414d9b14d178670d782ce25d/kubernetes/falco/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aks-falco
  namespace: falco-system
  labels:
    app.kubernetes.io/name: aks-falco
    app.kubernetes.io/instance: falco
    app.kubernetes.io/version: "0.33.1"
